SET IDENTITY_INSERT [dbo].[TblTopic] ON
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (1, N'Artificial Neural Net', N'neuron')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (2, N'Artificial Neural Net', N'neuroscience')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (3, N'Networking', N'ping')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (4, N'Networking', N'Protocols')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (5, N'Networking', N'destination')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (6, N'Learning Neural Network Structure', N'bayesian')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (7, N'Learning Neural Network Structure', N'network')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (8, N'Learning Neural Network Structure', N'statistical')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (11, N'Learning Neural Network Structure', N'overfitting')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (12, N'Learning Neural Network Structure', N'architecture')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (13, N'Learning Neural Network Structure', N'optimal')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (14, N'Learning Neural Network Structure', N'brain')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (15, N'Learning Neural Network Structure', N'damage')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (17, N'Learning In MultiLayer Networks', N'multilayer')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (18, N'Learning In MultiLayer Networks', N'gradient')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (19, N'Learning In MultiLayer Networks', N'propagation')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (20, N'Learning In MultiLayer Networks', N'weight')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (21, N'Learning In MultiLayer Networks', N'rule')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (22, N'Learning In MultiLayer Networks', N'update')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (23, N'Learning In MultiLayer Networks', N'logistic')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (24, N'Learning In MultiLayer Networks', N'logistics')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (25, N'Learning In MultiLayer Networks', N'regression')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (26, N'MultiLayer Feed Forward Neural Network', N'arbitrary')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (85, N'substance use', N'substance')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (27, N'MultiLayer Feed Forward Neural Network', N'depth')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (28, N'MultiLayer Feed Forward Neural Network', N'linear')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (29, N'MultiLayer Feed Forward Neural Network', N'regression')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (30, N'MultiLayer Feed Forward Neural Network', N'sigmoid')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (31, N'MultiLayer Feed Forward Neural Network', N'network')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (32, N'MultiLayer Feed Forward Neural Network', N'bumps')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (33, N'MultiLayer Feed Forward Neural Network', N'accuracy')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (34, N'MultiLayer Feed Forward Neural Network', N'structure')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (35, N'NULLSingle Layer Neural Network / Perceptron', N'perception')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (36, N'Single Layer Neural Network / Perceptron', N'learning')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (37, N'Single Layer Neural Network / Perceptron', N'perceptron')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (38, N'Single Layer Neural Network / Perceptron', N'gradient')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (39, N'Single Layer Neural Network / Perceptron', N'descent')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (40, N'Single Layer Neural Network / Perceptron', N'logistic')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (41, N'Single Layer Neural Network / Perceptron', N'nascent')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (42, N'Single Layer Neural Network / Perceptron', N'complex')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (43, N'Single Layer Neural Network / Perceptron', N'majority')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (44, N'Single Layer Neural Network / Perceptron', N'threshold')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (45, N'Neural Network Structure', N'nodes')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (46, N'Neural Network Structure', N'links')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (47, N'Neural Network Structure', N'sigmoid')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (48, N'Neural Network Structure', N'feed')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (49, N'Neural Network Structure', N'forward')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (50, N'Neural Network Structure', N'recurrent')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (51, N'Neural Network Structure', N'upstream')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (52, N'Neural Network Structure', N'downstream')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (53, N'Neural Network Structure', N'directed')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (54, N'Artifical Neural Network', N'computation')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (55, N'Artifical Neural Network', N'brain')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (56, N'Machine Learning', N'classification')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (57, N'Machine Learning', N'algorithm')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (58, N'Machine Learning', N'vectors')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (59, N'Machine Learning', N'machine')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (60, N'Machine Learning', N'learning')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (61, N'Machine Learning', N'vector')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (62, N'Machine Learning', N'algorithms')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (63, N'Machine Learning', N'datamining')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (64, N'Machine Learning', N'reinforcement')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (65, N'Machine Learning', N'information')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (66, N'Machine Learning', N'retrieval')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (67, N'Machine Learning', N'neural')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (68, N'Machine Learning', N'markov')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (69, N'Machine Learning', N'marvin')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (70, N'Machine Learning', N'minsky')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (71, N'Machine Learning', N'cognitive')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (72, N'Machine Learning', N'agents')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (73, N'Machine Learning', N'computational')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (74, N'Machine Learning', N'swarm')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (75, N'Machine Learning', N'rodney')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (76, N'Machine Learning', N'brooks')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (77, N'Machine Learning', N'efficient')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (78, N'Machine Learning', N'parallel')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (79, N'Machine Learning', N'socioeconomics')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (80, N'Machine Learning', N'humans')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (81, N'Machine Learning', N'ai')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (82, N'Machine Learning', N'artificial')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (83, N'Machine Learning', N'intelligence')
INSERT INTO [dbo].[TblTopic] ([Id], [TopicName], [Keyword]) VALUES (84, N'Artificial Neural Network', N'ann')
SET IDENTITY_INSERT [dbo].[TblTopic] OFF
